backend:
  name: github
  repo: estebanmenendez/astrowind
  branch: main
  base_url: https://www.wsriocuareim.com
  auth_endpoint: https://github.com/login/oauth/authorize
  
media_folder: "public/assets/images" # Dónde se guardarán las imágenes que suban los administradores
public_folder: "~/assets/images" # Cómo leerá Astro la ruta de esas imágenes

collections:
  - name: "eventos"
    label: "Eventos y Rodadas"
    folder: "src/content/post" # Ruta donde Astrowind guarda los artículos del blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del Evento", name: "title", widget: "string" }
      - { label: "Subtítulo / Breve Resumen", name: "excerpt", widget: "string", required: false }
      - { label: "Fecha de Publicación", name: "publishDate", widget: "datetime" }
      - { label: "Imagen de Portada", name: "image", widget: "image" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Eventos", "Rodadas", "Filantropía", "Asambleas"] }
      - { label: "Etiquetas (Separadas por coma)", name: "tags", widget: "list", required: false }
      - { label: "Cuerpo del Texto / Detalles", name: "body", widget: "markdown" }
