backend:
  name: github
  repo: estebanmenendez/ws_rio_cuareim
  branch: main
  base_url: https://oauth.decapcms.org # <-- CORREGIDO: El puente también va aquí para evitar el bloqueo de seguridad
  auth_endpoint: /prod/auth

media_folder: "public/assets/images"
public_folder: "~/assets/images"

collections:
  - name: "eventos"
    label: "Eventos y Rodadas"
    folder: "src/content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título del Evento", name: "title", widget: "string" }
      - { label: "Subtítulo / Breve Resumen", name: "excerpt", widget: "string", required: false }
      - { label: "Fecha de Publicación", name: "publishDate", widget: "datetime" }
      - { label: "Imagen de Portada", name: "image", widget: "image" }
      - { label: "Categoría", name: "category", widget: "select", options: ["Eventos", "Rodadas", "Filantropía", "Asambleas"] }
      - { label: "Etiquetas (Separadas por coma)", name: "tags", widget: "list", required: false }
      - { label: "Cuerpo del Texto / Detalles", name: "body", widget: "markdown" }
